language: go
go:
- master
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- make clean
install:
- make ensure
script:
- make test

notifications:
  email: false
env:
  global:
  - secure: 1Z0dqoUnkkLkAug+eITxVH3tZxSwDl4GlOISMKOyBxnQ6qUTpNUufP9UQMJqYpzZb+gFTZd7Oe0Tl3d/OLCpC8ATRlxA1E9sRjTydrrBOb5reZ2RhLJL7lW/JSkWh3ekod0tM3L/6FZM6/7c5tEVjfAawcGlOiPYNyBek24njnEyvabOvlW0pNup6uBG0YGD96iw07ftd0K4ZFD9Y8NQqP1doJ8SotvJHUcMh9gbIaQXvpwbMUXnAauNq8sJrMosP2ZFf1sh6doYroCCWu95EUBXBxAIuPai0D4n7ruhxsbywxxb3eHzDFwOxcy3tz/yQugpKt6Kau3FD0DkbqXb8D38+aVBfWHQb0b75SIfg1mTg2WKinfL4VRhUlDS7htvqAg+zc+S7dUixCqWLjlGwgrgnauAS5JnzAajNCnRm/lFTjZzF5KoSHkku4KdnMGFJoVgihOiiibAQLeGLX6A2KXqW1jn6CgmTz+Wfk6HUP6BJP6qBv0ScJhP8KgY1AYUNvbc3biQsNxdTZt76+h049jx8G1irLksUp4Jee5b1LN5NPXEZwXId7NgTGL54PaOKM9IlIVncbNo0IUJ6LIbJS/VdSynxOlIB8/e+QWzchkR+ggjFTVreG7L+UznWPzsNVgS30r/OeIJaYrHhrXagTlI6ibMjheCKRxlTxJ7rNc=
